/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author ferdio
 */
public class menu_utama1 extends javax.swing.JFrame {
    
    koneksi k = new koneksi();
    private Timer timer;

    /**
     * Creates new form menu_utama
     */
    public menu_utama1() {
        initComponents();
        this.setExtendedState(menu_utama1.MAXIMIZED_BOTH);
        k.connect();
        execute();
        
        //membuat timer
        timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            showTime();
            }
        });
        
        //memulai timer
        timer.start();
        
    }
    
    private void showTime(){
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy  HH:mm:ss");
        String dateTime = dateFormat.format(now);
        lb_tanggal.setText(dateTime);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_navbar = new javax.swing.JPanel();
        lb_tanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_sidebar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnl_menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pnl_content = new javax.swing.JPanel();
        pnl_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_navbar.setBackground(new java.awt.Color(25, 118, 211));
        pnl_navbar.setPreferredSize(new java.awt.Dimension(872, 70));

        lb_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        lb_tanggal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lb_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        lb_tanggal.setText("Tanggal dan Waktu");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_male_user_50px.png"))); // NOI18N
        jLabel1.setText("Staff");

        javax.swing.GroupLayout pnl_navbarLayout = new javax.swing.GroupLayout(pnl_navbar);
        pnl_navbar.setLayout(pnl_navbarLayout);
        pnl_navbarLayout.setHorizontalGroup(
            pnl_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                .addComponent(lb_tanggal)
                .addContainerGap())
        );
        pnl_navbarLayout.setVerticalGroup(
            pnl_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_navbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_tanggal)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(pnl_navbar, java.awt.BorderLayout.PAGE_START);

        pnl_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_sidebar.setPreferredSize(new java.awt.Dimension(250, 425));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        pnl_menu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_menu.setLayout(new javax.swing.BoxLayout(pnl_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pnl_menu);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnl_sidebar, java.awt.BorderLayout.LINE_START);

        pnl_utama.setBackground(new java.awt.Color(255, 255, 255));
        pnl_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnl_contentLayout = new javax.swing.GroupLayout(pnl_content);
        pnl_content.setLayout(pnl_contentLayout);
        pnl_contentLayout.setHorizontalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
        );
        pnl_contentLayout.setVerticalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pnl_utama.add(new bg_content());
        pnl_utama.repaint();
        pnl_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login1 login = new Login1();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_tanggal;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_navbar;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.JPanel pnl_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconMaster        = new ImageIcon(getClass().getResource("/image/icons8_data_recovery_30px.png"));
        ImageIcon iconTransaksi     = new ImageIcon(getClass().getResource("/image/icons8_split_transaction_30px.png"));
        ImageIcon iconLaporan       = new ImageIcon(getClass().getResource("/image/icons8_edit_graph_report_30px_1.png"));
        ImageIcon iconDataCustomer  = new ImageIcon(getClass().getResource("/image/icons8_customer_insight_30px.png"));
        ImageIcon iconKaryawan      = new ImageIcon(getClass().getResource("/image/icons8_management_30px.png"));
        ImageIcon iconHome          = new ImageIcon(getClass().getResource("/image/icons8_home_30px.png"));
        ImageIcon iconKasir         = new ImageIcon(getClass().getResource("/image/icons8_checkout_30px.png"));
        ImageIcon iconPengeluaran   = new ImageIcon(getClass().getResource("/image/icons8_exchange_30px_1.png"));
        ImageIcon iconPemasukan     = new ImageIcon(getClass().getResource("/image/icons8_deposit_30px.png"));
        ImageIcon iconOrder         = new ImageIcon(getClass().getResource("/image/icons8_order_history_30px.png"));
        
        
        menu_item masBarang1    = new menu_item(null, true, iconDataCustomer, "Data Customer", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnl_utama.removeAll();
                pnl_utama.add(new Form_Data_Customer());
                pnl_utama.repaint();
                pnl_utama.revalidate();
            }
        });
        
        menu_item masBarang2    = new menu_item(null, true, iconOrder, "Order", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnl_utama.removeAll();
                pnl_utama.add(new Form_Order());
                pnl_utama.repaint();
                pnl_utama.revalidate();
            }
        });
        
        menu_item masTransaksi1    = new menu_item(null, true, iconKasir, "Kasir", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnl_utama.removeAll();
                pnl_utama.add(new Form_Transaksi());
                pnl_utama.repaint();
                pnl_utama.revalidate();
            }
        });
        
        menu_item masTransaksi2    = new menu_item(null, true, iconPengeluaran, "Pengeluaran", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnl_utama.removeAll();
                pnl_utama.add(new Form_Pengeluaran());
                pnl_utama.repaint();
                pnl_utama.revalidate();
            }
        });

        
        menu_item menuHome      = new menu_item(iconHome, false, null,"Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnl_utama.removeAll();
                pnl_utama.add(new bg_content());
                pnl_utama.repaint();
                pnl_utama.revalidate();
            }
        });
        menu_item menuMaster    = new menu_item(iconMaster, false, null,"Master", null, masBarang1,masBarang2);
        menu_item menuTransalsi = new menu_item(iconTransaksi, false, null,"Transaksi", null, masTransaksi1,masTransaksi2);

        
        addMenu(menuHome,menuMaster,menuTransalsi);
        
        
        
    }
    
    private void addMenu(menu_item... menu){
        for (int i = 0; i < menu.length; i++) {
            pnl_menu.add(menu[i]);
            ArrayList<menu_item> subMenu = menu [i].getSubMenu();
            
            for (menu_item m : subMenu) {
                addMenu(m);
            }
        }
        pnl_menu.revalidate();
    }
}
